services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    image: itsmeru/rate-limiter:latest
    container_name: rate_limiter_app
    ports:
      - "8501:8501"
    depends_on:
      - redis
    restart: unless-stopped
